### ISSUE TITLE
Question - Any guidelines or best practices for writing Hubot scripts with ES6

### ISSUE THREAD

**Issue by gavriguy** [github/hubot#1009]
Hi,
Are there any guidelines or best practices for writing Hubot scripts with ES6?
thanks

**Comment by technicalpickles** [comment]
I haven't seen or heard of anyone ES6 yet.

I think the main thing is going to be launching `node` with the --harmony command line flags for turning those on. You can see in [`bin/hubot`](https://github.com/github/generator-hubot/blob/master/generators/app/templates/bin/hubot) where hubot is launched. That scripts shebang is `#!/usr/bin/env coffee`, so it's loaded with coffee script. I suspect either coffeescript would need a way to turn those scripts on, or you'd need to change the way hubot is launched.

Sorry I don't have any more useful information for you, but please post back with how things go!

**Comment by cycomachead** [comment]
I'll :+1: ES6 support, but haven't seen much either.

I briefly looked into launching node with `--harmony` but wasn't able to easily figure anything out.

You can run hubot on iojs without much (any, probably) issues and that will give you a good start on ES6 features. However, I still haven't found an easy way to pass command line args to coffee script.

**Comment by technicalpickles** [comment]
> However, I still haven't found an easy way to pass command line args to coffee script.

`coffee --help` gives us:

      --nodejs       pass options directly to the "node" binary

**Comment by cycomachead** [comment]
You're right! I had tried that once, and didn't get it to work, but this does:
```
coffee --nodejs --harmony node_modules/.bin/hubot
```
(All args need to be _before_ the file to launch, which is what was tripping me up before.)

**Comment by hell0again** [comment]
I'm running hubot on node `v0.12.7`.
To run hubot on node, one more step was required.

Using ES6 (especially ES6 generators) in hubot script, CoffeeScript `^1.9.0` is required http://coffeescript.org/#1.9.0
Although hubot is using `1.6.3`, We can use another version of it for hubot scripts. see https://github.com/github/hubot/pull/863#issuecomment-75324905

**Comment by therynamo** [comment]
Just wanted to drop a comment for those who may come looking for answers.

I was able to get ES6 (ES2015) up and running with hubot fairly quickly with babel. It does require a build step, but it is pretty straight forward and you can write all the ES6 you like. 

(feel free to change the following setup, this was just an on the fly go at it)

My Setup:

Node: `v4.2.4`
NPM : `v3.X.X` (should be fine with 2)

Using [`babel-cli`](http://babeljs.io/docs/setup/#babel_cli), I was able to transpile my ES6 code from a separate directory, into my scripts directory. 

There was however one nuance. Hubot did start up, and did fire off other scripts, yet, it was not firing off my ES6 scripts. This was due to Babel's transpilation of `exports`. It will transpile: 

```JavaScript
export default (robot) => {
  robot.hear(/swing/, (res) => {
    res.send("swung");
  });
}
```

to 

```JavaScript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.default = function (robot) {
  robot.hear(/swing/, function (res) {
    res.send("swung");
  });
};
```

This looks fine, however, after some investigation (short investigation, I'll have you).  It appeared that Hubot was not happy about me not using `module.exports` instead. 

There is however a babel plugin that will get you quickly back on your feet. 

[Add Module Exports](https://github.com/59naga/babel-plugin-add-module-exports). 

This then allows my modules to export the default class using module.exports, like so:

```JavaScript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.default = function (robot) {
  robot.hear(/swing/, function (res) {
    res.send("swung");
  });
};

module.exports = exports['default'];
```

Really haven't been at it long, however I imagine with node `4.2.4` LTS having some native ES6 support, if you ran Hubot with that, you would be able to get the native features available there. Though I haven't played with it long enough to figure out completely since the build step is fine for me right now.

**Comment by cycomachead** [comment]
Thanks @therynamo !

> Really haven't been at it long, however I imagine with node 4.2.4 LTS having some native ES6 support, if you ran Hubot with that, you would be able to get the native features available there.

Yep! I can confirm this works. I'm using template literals in my code and it's great! Haven't done too much with other ES6 stuff, but so far the basic stuff I've tested seems great. v5 seems OK too, which is what I'm using for local dev, but I still deploy on v4.2, so I don't have much experience with those new features.

**Comment by therynamo** [comment]
Awesome! Yeah, that set up makes sense. Thanks for confirming @cycomachead!

**Comment by gilesvangruisen** [comment]
Hey everyone!! For what it's worth, I thought I'd share how I got hubot/ES6 working really easily, since I don't see mention of my solution here. 

Newer versions of Node support ES6 syntax by default, which is great, but unfortunately [generator-hubot](https://github.com/github/generator-hubot) still defaults to [specifying node version `0.10.x`](https://github.com/github/generator-hubot/blob/master/generators/app/templates/_package.json). I was running a recent version of Node on my laptop, so it all worked fine. But when it came time to deploy to Heroku, the app crashed because Heroku was using the version of Node specified in `package.json`.

To fix this, I simply changed the node engine in `package.json` to specify a newer version of Node, in my case `6.1.x`:
```
{
  ...
  "engines": {
    "node": "6.1.x"
  }
}
```

Hope this helps someone! Thanks for hubot btw :D

**Comment by drywheat** [comment]
@gilesvangruisen I'm using Node v8.1.x and, following your `package.json` instructions, I get an error when launching hubot if I have an ES6 script (i.e. scripts/foo.js).

Is that the ONLY step you performed or did you

1. Install other dependencies
2. Manually transpile your source in the manner described earlier in this thread

**Comment by gr2m** [comment]
@drywheat do you try to inherit from any of the Hubot classes in `scripts/foo.js`? The problem is that the classes exported by `require('hubot')` are compatible with CoffeeScript, not es2015 classes.

We are working on converting `hubot` to modern JavaScript, you can try it with the latest master of https://github.com/hubotio/hubot, then `require('hubot/es2015')`

**Comment by drywheat** [comment]
This is basically all there is inside of `foo.js` using Hubot v2.19.0:

```es6
export default (robot) => {
  robot.hear(/greet me/, (res) => {
    res.send("hello you!");
  });
}
```

If I leverage the latest master, where should I put that `require('hubot/es2015')` line? Should that be at the top of every script I write, or is there a single place to add it? 

**NOTE**: Right now I creating all of my scripts under `scripts`; I may move them to out to plugins later.

**Comment by gkadillak** [comment]
Here's what worked for me:

1. npm install babel-polyfill
1. npm install babel-register
1. create a file in the /scripts directory called `00-es6setup.js` with

```js
// enable ES6 goodness!
require('babel-register');
require('babel-polyfill');
```
and now you should be able to use es6 features in other hubot scripts
