### ISSUE TITLE
Middleware listening on enter aswell

### ISSUE THREAD

**Issue by vongohren** [github/hubot#1015]
I would just like to inform @michaelansel that the robot is running the middleware on the enter command aswell.
And in hipchat adapter, it runs the enter command for all users when joining a room.
Dont know if you want it to listen to enter or not?

**Comment by michaelansel** [comment]
Yes, that is expected behavior; middleware will execute for every matched Listener (regardless of type). If you want to filter, check to see what type of message is being processed ([just like the core does for routing](https://github.com/github/hubot/blob/master/src/robot.coffee#L144)). If this is a common need, I'll see about adding a helper to match the current Listener creation helpers.

(definitely an interesting use case I didn't consider)

**Comment by technicalpickles** [comment]
I have run into this too. I think there could be more explicit details on there, and the example documentation should demonstrate that, as that's the kind of listener most people are going to be using.
