### ISSUE TITLE
google.coffee is broken

### ISSUE THREAD

**Issue by n0mer** [github/hubot#1024]
https://github.com/github/hubot-scripts/blob/master/src/scripts/google.coffee

Always returns "Sorry, Google had zero results".

Is there any way to disable this script? Or remove it completely.

**Comment by kengz** [comment]
You can replace it with your own script. I realized the same issue and rewrote it, you can use too :)
here: https://github.com/kengz/jarvis
under `scripts/google.coffee`

**Comment by technicalpickles** [comment]
@n0mer you can remove "google.coffee" from your `hubot-scripts.json`. 

You can also try using https://github.com/mnpk/hubot-google , which is an updated version of it. @kengz you might find that useful too.

**Comment by n0mer** [comment]
@technicalpickles i override this script with `google.coffee` from https://github.com/kengz/jarvis

what about removing broken `google.coffee` from Hubot distribution?

**Comment by technicalpickles** [comment]
I'd happily accept a PR to do just that :grin: That said, we are trying to kill that repository over in https://github.com/github/hubot-scripts/issues/1641 and get people using scripts that have been packaged separately.

For that reason, I'd recommend using https://github.com/mnpk/hubot-google instead of just copying from jarvis. Otherwise, you'll have to keep copying down changes from that repository, rather than just updating the package cc @kengz
