### ISSUE TITLE
Can't make HTTP requests

### ISSUE THREAD

**Issue by ecnepsnai** [github/hubot#1060]
I'm trying to have hubot get stock quotes from a REST API.  I'm using the following script to accomplish this:

    module.exports = (robot) ->
        robot.hear /!ftnt/i, (res) ->
            res.robot.http('http://dev.markitondemand.com/Api/v2/Quote/json?symbol=ftnt')
            .get() (err, res, body) ->
                res.send "Got back #{body}"

However it always fails with the following stack:

> ERROR TypeError: undefined is not a function
>   at /home/ian/FortiFriend/scripts/ftnt.coffee:5:8
>   at IncomingMessage.<anonymous> (/home/ian/FortiFriend/node_modules/scoped-http-client/src/index.js:95:22)
>   at IncomingMessage.emit (events.js:129:20)
>   at _stream_readable.js:908:16
>   at process._tickCallback (node.js:355:11)

For reference, here is `/home/ian/FortiFriend/node_modules/scoped-http-client/src/index.js:95:22`:

     return res.on('end', function() {
         return callback(null, res, body);
     });

I'm using nodejs v0.12.7 on Ubuntu 15.04

**Comment by technicalpickles** [comment]
I think the problem is that the `res` in the `robot.hear` callback is overshadowing the `res` in the `get()` callback. Try:

```coffeescript
module.exports = (robot) ->
  robot.hear /!ftnt/i, (res) ->
    res.http('http://dev.markitondemand.com/Api/v2/Quote/json?symbol=ftnt')
      .get() (err, httpRes, body) ->
        res.send "Got back #{body}
```

See https://github.com/github/hubot/blob/master/docs/scripting.md#making-http-calls for some more information. In particular, you will want to check for an `err` and that  `httpRes.statusCode` is something you expect (ie 200 to indicate success) before touching `body`.
