### ISSUE TITLE
Allow multiple adapter connection

### ISSUE THREAD

**Issue by webhamm** [github/hubot#1075]
Is there a way to allow hubot to connect to and respond to multiple adapters like one for hipchat and one for slack?

**Comment by michaelansel** [comment]
Nope, not in the current implementation. There was conversation at one point about building a proxy that would duplicate messages out to multiple hubot instances, but I don't think it was ever built. There are a lot of assumptions in the core that there is one and only one adapter, but that could change if there was significant need (probably not high on our priority list though).

**Comment by coagmano** [comment]
If you don't care about communicating across, you could run two instances with different env vars and arguments?

**Comment by webhamm** [comment]
@michaelansel thanks for the response. We are trying out Hubot. Sadly :crying_cat_face:  having multiple instances to get around this issue.

**Comment by technicalpickles** [comment]
cc https://github.com/github/hubot/issues/122 https://github.com/github/hubot/pull/133 https://github.com/github/hubot/issues/507 for prior discussions

The hardest part is persistence. Let's say we are using slack and campfire. Users are stored in the brain by their id, according to the adapter's backend. Campfire uses integers, and Slack uses U + integers (U1234). If a person has a campfire account and a slack account, is there an expectation that anything persisted to a user in the brain is accessible from either end? Also worth noting there's a flat namespace, so if there's two adapters connected that both use strings or integers as ids, you could get the wrong user.

**Comment by kirbo** [comment]
This would make my day, I have huge need to communicate between multiple adapters (let's say that if one says a command on irc, the hubot should execute a command in twitch and if one says some specific command/words on twitch, the bot should say something different on irc and make an api call).
Don't know if there is any better way to do this right now, but now i'm approaching this "issue" in a way that the bot adds a row in the database (via api) and every adapter checks the new lines (from api) every now and then and if there is a specific like in the database, hubot does something. This just feels way too dirty/hacky because i need to poll the api from 3 different adapters lets say every 5 seconds, just to check if the bot should do something.

**Comment by till** [comment]
As a reference for whoever Googles this tomorrow.

I am running "1" hubot app on Heroku but it connects to different chats. So that one app can re-use environment variables, etc..

My heroku `Procfile`:

```
fd: bin/hubot -a flowdock
hc: bin/hubot -a hipchat
```

Then I just scaled those up (and turned web off):

```
$ heroku ps:scale web=0 fd=1 hc=1
```

**Comment by DavidAwad** [comment]
+1 to this being important to do, I think the best way is for each adapter to maintain it's own redis keys using the names of the services as prefixes to keep the ids unique.

**Comment by technicalpickles** [comment]
This would be a good one for the [hubot evolution](https://github.com/hubotio/evolution/) process if anyone is interested in thinking through it.

**Comment by MothGirlMusic** [comment]
so... does hubot support multiple adapters yet?
