### ISSUE TITLE
Documentation for messageRoom etc?

### ISSUE THREAD

**Issue by framerate** [github/hubot#1085]
I can't seem to locate documentation for `messageRoom` anywhere. I'm using it based on the ONE mention I found here: https://hubot.github.com/docs/scripting/

I'm interested in sending direct messages back to the person who requests something and feel like I'm missing a clear documentation someplace? 

If it doesn't exist, I can help write it if someone can help fill me in!

**Comment by GSAgentP** [comment]
@framerate I forked help.coffee and do something similar, rather than spamming a room it sends the user who requested help a PM with the content. Depending on which adapter you use, you should be able to see the JID of the user as part of the msg envelop:

'''javascript
robot.send(jid, emit) 
'''

 jid is the JID for the user, and emit is list of commands generated by help. You should be able to find the jid as part of the original msg object, (msg.message.user.id.jid(

**Comment by framerate** [comment]
@GSAgentP  Thanks for that. 

Hubot is a lot of fun but feels a little like abandon-ware. I'd love to see the documentation get up to snuff. If anyone at Github wants to come up with a plan of attack I'd love to help getting it there.

**Comment by GSAgentP** [comment]
@framerate I don't think I'd call it abandonware, I'd call it a side project. :) 

On my team, we use Hubot almost exclusively to manage our 'chat ops' strategy, I have it integrated with every major tool we use, and we've written a bunch of stuff just for fun. It's taken me over a year to get it to the point where I am comfortable calling it 'production ready'. I used a lot of the scripts GitHub built as a base, and did a ton of tweaking due to the size of our teams and integration. I'm hoping to contribute back everything we've written, but being corporate I have to jump through a few hurdles first.. We'll see.

But either way, it's open source :) You get out of it what you contribute, and you can't expect the creators to do everything.

**Comment by framerate** [comment]
@GSAgentP Oh for sure. I'm just saying I'm willing to contribute so other people aren't confused by the lacking documentation, just not really sure where to start. But I guess I can dig through the source!

**Comment by technicalpickles** [comment]
@framerate I'm sorry that hubot seems like abandonware to you. Personally, I've been working on a pretty huge internal project so haven't made time to work on hubot's core (you can see some of that work in https://github.com/github/hubot-slack/issues/2 though). That wrapped up just before the holidays, so you can probably see me triaging things now if you watch the repo.

As for `messageRoom`, you've already found the scripting in [scripting.md](https://github.com/github/hubot/blob/master/docs/scripting.md), that'd be the place any documentation should go. The code for it here: https://github.com/github/hubot/blob/master/src/robot.coffee#L552-L560 . You can see some code comments there (https://github.com/github/hubot/issues/997 for tracking generating code documentation). I can't think of a time I've used this particular function though, so I don't have much more insight.

**Comment by framerate** [comment]
@technicalpickles I meant no disrespect, my good man! I love what you guys have done here. I'd love to help!

I use hubot via slack. The plugin I was writing did an update every morning around 9am to a certain channel and would update everyone on how many users joined the previous day and other stats. Simple stuff like that. 

I'll add to my todo list to try and help out with the stuff I learned into the docs and issue a PR!

**Comment by twellspring** [comment]
@technicalpickles I am pretty new to hubot and doing the same thing.   When I start contributing to a new open source project, documentation is an easy starting place, and I frequently learn things that I can use when I update the documentation.   Like this one.  I have an immediate use for messageRoom.  Pull request coming for this documentation.

**Comment by mose** [comment]
Doc updated, issue solved :) great move.
