### ISSUE TITLE
Modify the default parameterLimit value in robot's express 

### ISSUE THREAD

**Issue by gotchahn** [github/hubot#1105]
Right now I use Hubot with `Chargify` like webhook and I am getting some `413 Request entity too large` with some events.
Digging we found that here: https://github.com/github/hubot/blob/master/src/robot.coffee#L430 , `robot` initialize the `express` object and call `app.use express.urlencoded()` without options. 

How can we modify the `paramLimit` for not getting `413` often: https://github.com/expressjs/body-parser#bodyparserurlencodedoptions ?

**Comment by technicalpickles** [comment]
In general, I'd like to try to extract express out of hubot's core, just because there are so many ways to configure it, and there's no end game for exposing more things as environment variables. You can see how many there are in https://github.com/github/hubot/issues/1106 already.

I think this approach is okay for now, but I think https://github.com/github/hubot/issues/767 is the goal long term. https://github.com/github/hubot/pull/1110 is some work I started to enable some of that.
