### ISSUE TITLE
call robot.run() only when all scripts are done loading

### ISSUE THREAD

**Issue by kengz** [github/hubot#1126]
When the robot is done being constructed, the last thing to be called is [`robot.run()`](https://github.com/github/hubot/blob/master/bin/hubot#L135). However, there's no guarantee that the script-loading step before it would complete before `run()` is called.

To allow for proper control and for scripts to make use of the event "running", can we make the emission happen after scripts load? Possible applications include loading an external database, serializing all users in a channel only when all scripts are loaded, or auto-running initialization tasks when the bot is completely loaded.

**Comment by technicalpickles** [comment]
`run()` is actually the function that kicks everything off. it emits `running` and starts the adapter https://github.com/github/hubot/blob/master/src/robot.coffee#L588-L590 . The scripts aren't registered until after the adapter is connected https://github.com/github/hubot/blob/master/bin/hubot#L133 . That is necessary, because some adapters will make changes to the robot at run time (Slack sets the bot name based on the bot user).

Are there specific problems you are running into with the way it currently works? Also of interest is work in https://github.com/github/hubot/pull/1110 and https://github.com/github/hubot/issues/858 to have more control over bot initialization.

**Comment by kengz** [comment]
@technicalpickles I see, thanks for the clarification and references.

An example would be to automatically serialize all users in the room when the robot is fully loaded. This is done via a script, which has to be called automatically when the adapter is connected, and the robot is fully ready.

Ideally, the script can be a method called when the entire robot is completely loaded, say if it emits and event 'ready'. Then the handler in the script can pick it up and execute cuz it would have been loaded before the event emission. It is crucial that at least the adapter is already loaded to get the `brain.data.users`, and that the event be emitted after the script is loaded for it to handle.

Below is one example:
```js
module.exports = function(robot) {
  // serialize on running
  robot.on('ready', function() {
    serialize_users(robot.brain.data.users).then(function(size) {
      var str = 'Serialized ' + size + ' users.'
      robot.messageRoom('general', str)
    })
  })
```
