### ISSUE TITLE
Raven does not report uncaught exceptions

### ISSUE THREAD

**Issue by preynal** [github/hubot#1131]
Hello, 
I'm trying to use raven from [sentry](http://getsentry.com) to report exceptions. The problem is that hubot has its own process.on "uncaughtException" listener, so my exception tracking does not work.
Also, when an exception is thrown and not handled, it is best practise to restart the program, because it is in an unknown state. 
I understand you're doing this to improve the developer experience.

Is there any way to remove this behaviour ?
Would you accept a patch where the exception handling can be disabled via some sort of --no-exceptions-handler flag ?

Cheers

**Comment by technicalpickles** [comment]
Hubot has a mechanism for reporting errors it catches: https://github.com/github/hubot/blob/master/docs/scripting.md#error-handling . I would try that first.

You are right that it's to improve developer experience, but also user experience. I understand that it is said that uncaught errors leave the process in an unknown state, but I haven't seen any impact due to this in practice.

I would look at using domains before just disabling the exception handlers (although, it seems in latest nodes even domains are deprecated, soooo).

**Comment by preynal** [comment]
I appreciate that you haven't seen this in practice, but even the document you mentioned quotes: 

"The uncaughtException handler [technically leaves the process in an unknown state](http://nodejs.org/api/process.html#process_event_uncaughtexception)."

It is not really about the raven client, but the fact that as a user (as in: a developer trying to deploy and monitor hubot sanely), I need to have control over how my process handles failures.

**Comment by technicalpickles** [comment]
Better error handling is something I'd be interested in for sure.

We're in the process of getting hubot back into a maintained state, and modernizing it, and I think that would fit into it well. We are using [Hubot Evolution](https://github.com/hubotio/evolution) to propose, discuss, approve, and implement new features / improvements, so I'd encourage anyone interested to check that out.
