### ISSUE TITLE
does hubot support default response?

### ISSUE THREAD

**Issue by bdcwq** [github/hubot#1184]
does hubot support default reponse? like 
hubut> @hubut are you ready?
hubot> I dont know what's mean.

**Comment by technicalpickles** [comment]
There's `robot.catchAll`. https://github.com/github/hubot/blob/master/docs/implementation.md#message-processing talks about it, but it's not in the scripting documentation.

There's some limitations to it's current use right now, where it only happens if nothing matches the text. This includes people talking to other people, and not the robot. In a `catchAll` you could work around this by checking the message's text to see if it matches `robot.respondPattern`.
