### ISSUE TITLE
reuse of variable in scripting docs

### ISSUE THREAD

**Issue by digininja** [github/hubot#1241]
In most of the docs you use the variable res as the parameter passed in when scripts start, i.e. an instance of Response.

In this section of the docs:

https://hubot.github.com/docs/scripting/#making-http-calls

res is reused as "res is an instance of node's http.ServerResponse."

I've just struggled for an hour trying to use res to send a message back to the room after doing a HTTP request before I finally noticed that in the snippet of code I'd taken from the example redeclared res and so it was no longer an instance of Response.

I'd suggest rewriting these examples to use a different parameter name to preserve the original Response instance to help with both clarity and to prevent others from getting stuck like I did.

**Comment by mose** [comment]
After historical research I found out that the previous var name was `msg` and more recent documentation uses `res` as a variable used in `robot.respond` function, in the documentation. I think it was not seen as a problem because `robot.router.*` functions are not really inter-scoping with the `robot.respond` ones.

This is something we will have to make sure it's taken in account for the next hubot 3 version.

**Comment by technicalpickles** [comment]
> I think it was not seen as a problem because robot.router.* functions are not really inter-scoping with the robot.respond ones.

@mose this is about making HTTP requests (with [scoped-http-client](https://github.com/technoweenie/node-scoped-http-client)) in `robot.respond` blocks, which is super common.
