### ISSUE TITLE
Something wrong in doc

### ISSUE THREAD

**Issue by zyf0330** [github/hubot#1285]
In this [HUBOT making-http-calls](https://hubot.github.com/docs/scripting/#making-http-calls), code like this
```
robot.http("https://midnight-train")
    .get() (err, res, body) ->
``` 
is not proper. Above example code about `robot.hear` etc use `res` as callback param. So it will make people misunderstanding between these two `res`.

**Comment by mose** [comment]
Yes this is a recurring feedback. @technicalpickles we should do something about it. Before it was `(msg)` why was it changed to `(res)` actually?

**Comment by michaelansel** [comment]
Because the object being passed is a `Response` object, not a `Message` object 😉 That said, this is definitely recurring feedback that we should consider for v3.

**Comment by zyf0330** [comment]
I just didn't consider more about v3.😥
Just think this is a misunderstanding param name.

**Comment by technicalpickles** [comment]
It's as @michaelansel said. The parameter to `respond`/`hear` etc is a  `Response` object. I'm not sure which is more confusing, it being `msg` and having `msg.reply` and `msg.message.name` or being `res.reply` and `res.message.name`. It gets more complicated when you make HTTP requests with a respond block, because now you are overloading `res`. It's probably okay to overload it, in practicl terms, but linters are definitely going to complain.

https://github.com/github/hubot/issues/786 is where we tried to update documentation to prefer `res`

**Comment by mose** [comment]
In doc we could change the `res` from http to `response`, maybe that would help. (and remove the half-dozen still surviving `msg` in scripting.md). WDYT?

**Comment by mose** [comment]
Doc has been fixed with clearer distinction.
