### ISSUE TITLE
[Question] Is Hubot still being maintained?

### ISSUE THREAD

**Issue by jason-riddle** [github/hubot#1307]
The commit activity seems to have slowed down with the last commit being at May 14th, 2016 while the issues and open pull requests seem to be accumulating. Is the project still being maintained?

**Comment by timkinnane** [comment]
I started watching this repo a few weeks ago to find that out, ironically this is the first issue to come up. I've asked on the subreddit too, but not much going on there. One response was that the core is generally stable and full featured, so most activity is on the adapters and external scripts / node packages. Which makes kind of sense, since hubot is like a chat-bots kernel, you wouldn't expect it to change much once its in wide use and well documented.

I'd generally like to know where the hubot community is to gauge what's going on in the space. There's some activity on reddit, stack overflow, gitter, twitter, but no idea if any of those are the best place to start a discussion.

**Comment by mose** [comment]
There is some life sometimes on freenode `#hubot` irc channel.

**Comment by matteoredaelli** [comment]
Should I start a new project using this code no more maintained?

**Comment by jason-riddle** [comment]
@timkinnane That makes sense about core being stable. I was mainly thinking about npm package upgrades and security updates.

**Comment by hakusaro** [comment]
I think it's a relevant question to ask. "V3" has been on the roadmap for a long time and never been finished. Maybe a Githubber can chime in?

**Comment by bkeepers** [comment]
@jason-riddle thanks for asking. The timing was pretty perfect because just days before you opened this I transitioned into a new role as product lead for Hubot.

I just opened https://github.com/github/hubot/pull/1321 to start discussing the roadmap for Hubot v3:

> For the past couple years, we’ve considered Hubot “stable”. We have a ton of infrastructure built on top of it and it does what we need. But now we want to take it to the next level.
>
> We’re ready to start working on Hubot v3, which aims to be a bot framework optimized for developers and developer workflows, with great integration in the most popular chat clients and developer tools, and an active community that is sharing scripts and best practices.

Check out the PR and let us know what you think.
