### ISSUE TITLE
Allow execution of hubot command from CLI

### ISSUE THREAD

**Issue by patcon** [github/hubot#613]
I'm interested in programmatically running some quick hubot commands in the interest of auto-generating documentation.

Ideally, would be great to add an argument to the shell adapter that would allow this (with the [sample script](https://github.com/hubot-scripts/hubot-example/blob/master/src/hello-world.coffee)):

```
$ bin/hubot -u user1 -e "hubot: hello"
user1: hello!
$ bin/hubot -u user1 -e "and so I says to the guy 'orly you don't say'"
yarly
```

**Comment by geoffreyanderson** [comment]
I wonder if this might help with problems that folks are encountering from some IDEs when trying to run in debug mode (like #648).  At present, you need to run node-inspector and then invoke hubot through coffeescript with a `--nodejs --debug` flag in order to start walking the code.  Having a syntax to directly invoke a command on bot execution (e.g. `bin/hubot -e "hubot: ping"`) might simplify some specific testing/debug cases from an IDE perspective.  It's also possible that these IDEs just need to fix their darn debugger integration and then maybe this isn't as necessary.

**Comment by ericdorsey** [comment]
I would like to see this feature too! 

+1 to @coderofsalvation's unix-foo in the meantime, that worked for me (ie, the `expect` command)

**Comment by coderofsalvation** [comment]
thnx. Meanwhile i use:

    $ ./testhubot mustache me chucknorris

as i turned it into a bashscript [testhubot](https://gist.github.com/coderofsalvation/9907f752e827de15559d)

**Comment by technicalpickles** [comment]
I mentioned knowing when a script was done was one problem. I mention another over in https://github.com/github/hubot/issues/904

> Adapters must emit a 'connected' event at some point, bin/hubot has a listener for that event to actually load scripts (https://github.com/github/hubot/blob/master/bin/hubot#L128-L133). Feasibly could add another event to robot like 'scriptsLoaded', that the adapter could listen for.

Basically, hubot doesn't currently know when the scripts are loaded, so that it could `robot.receive` a message from the command line.

**Comment by mose** [comment]
The `expect` solution with a generous sleep seems to make the trick. I'm going to close this issue :)
