### ISSUE TITLE
Override help command

### ISSUE THREAD

**Issue by jaxxstorm** [github/hubot#844]
Is it possible to override the help command to not have it spam a chat channel, maybe return a URL?

**Comment by technicalpickles** [comment]
The help command was actually extracted out to a separate package: https://github.com/hubot-scripts/hubot-help

It is a little bit tricky, because it's adapter specific how multi-line messages are handled. In things like Campfire and Slack, they are 'pasted' as a single message, but irc would send multiple messages flooding the channel as you said.

Feasibly, you could check `robot.adapterName` and do adapter-specific behavior in scripts.

**Comment by jaxxstorm** [comment]
I've basically overrode my package.json and forked the code for hubot-help, that does the trick. Not ideal, but it works. 

Thanks @technicalpickles

**Comment by technicalpickles** [comment]
@jaxxstorm glad that worked! if you want to contribute those changes back, I'm sure others could benefit from it.
