### ISSUE TITLE
Docs: Getting commands from external script to show up in `help`

### ISSUE THREAD

**Issue by sommestad** [github/hubot#851]
We've [developed a Hubot script](https://github.com/Springworks/hubot-tsheets) for integration with a time-tracking service.

It worked great, but for one thing: the commands doesn't show up. 

After digging around in the Hubot source, I realized that my project structure was to blame:

```
// `tsheets.coffee` loaded files from `lib`
| lib
| package.son
| tsheets.coffee
```

Appearantly, the structure has to be something along the lines of:

```
// `tsheets.coffee` loaded from `index.coffee`
| src (maybe works with other name as long as index.coffee loads file)
  |_ tsheets.coffee
| index.coffee
```

If this is a requirement for things to work, you might want to clarify it in the docs. :)

Thanks for a great product.

**Comment by technicalpickles** [comment]
@sommestad that is a good point. One thing to understand about building scripts as package is that they are `require`d, which looks at the package.json's main attribute to figure out what to require inside the package. The [scripting documentation](https://github.com/github/hubot/blob/master/docs/scripting.md#creating-a-script-package) talks about it at the very end a little bit.

How did you create this package? We have a [yeoman](http://yeoman.io/) [hubot generator](https://github.com/github/generator-hubot) which can make script packages, which should take care of most of this for you.

**Comment by technicalpickles** [comment]
Had another thought about this.

To be a bit more clear, hubot doesn't really any expectations about how a script package is laid out, directory wise. hubot does a `require` of the package (https://github.com/github/hubot/blob/master/src/robot.coffee#L263), and expects it to export a function, which is then called with `robot`. You just have to make sure the `robot.loadFile` happens for the hubot scripts.

Alternatively, this could suggest that it should be simpler, since it's a bit confusing, and there's some boiler plate in index.coffee. @michaelansel your ideas in  https://github.com/github/hubot/issues/858 around having a different API for script packages might be applicable here.

**Comment by optical** [comment]
For what its worth, I just had this problem myself - trying to get my external script package to register its documentation. To be clear I had no problem getting the package working, just had no idea how hubot might search for documentation in packages (it doesn't).

The simplest solution for me seems to be to make my main file export nothing more then a simple function which will call `robot.loadFile` on the actual entrypoint to the package, so that the documentation gets parsed.

It'd be nice if this were a little clearer in the documentation. Additionally perhaps hubot should parse the modules main file, or have some way of locating a packages documentation through properties on project.json or similar?

**Comment by wonkodsane** [comment]
Concur on making this clearer in the documentation and making it easier to implement from external scripts.

It's a little silly to have to duplicate the exact same loadFile process in a separate index.coffee file for every single module. Doesn't this defeat the purpose of abstraction?

Help should change to account for a default behavior or parseHelp should be called differently.
