### ISSUE TITLE
Have hubot respond to everything EXCEPT robot.respond?

### ISSUE THREAD

**Issue by michaeljhopkins** [github/hubot#866]
`robot.hear` is triggered for every message. And `robot.respond` is only triggered where the message starts with the robots name. Is there a way to trigger only if the message doesn't start with the robots name?

**Comment by rcarson** [comment]
You should be able to add a listener with a negative look ahead

    robot.hear("^(?!.*[Hh]ubot).*$", callback)

Not sure if this is correct coffeescript syntax or not, but the idea should be the same.

**Comment by technicalpickles** [comment]
```coffeescript
robot.hear("^(?!.*[Hh]ubot).*$", callback)
```

The problem with this regex is that it's hard-coded to hubot, not whatever your bot name might be. In `robot.respond`'s code, you can see how it builds up a regex for the robot's name: https://github.com/github/hubot/blob/master/src/robot.coffee#L88-L113

So, feasibly can do that, but then negate it. If it were useful to be in hubot's core, I'd tentatively throw out a name for the method like `robot.eavesdrop`.

**Comment by michaelansel** [comment]
A quick brainstorm building on the refactor in #868

```coffeescript
robot.eavesdrop = (pattern, callback) ->
  negativePattern = @respondPattern /.*/
  robot.hear pattern, (response) ->
    if not response.message.match negativePattern
      callback()
```

Known issue: this will block the fallback to catchall because the listener has already matched

There might be a way to solve this by wrapping similar logic around `TextListener.match`. This might also be a use case for pre-match middleware ("receive middleware").

An extension to `TextListener.match` with a pattern to not match seems like it might be the best solution (rather than building a new regex).

**Comment by michael-hopkins** [comment]
@michaelansel possibly bug, possibly feature. Basically, i'm looking to do one subset of instructions for `"hubot *"`, and a different subset of instructions for anything that is `!"^hubot"`. Pardon my pseudo code.

**Comment by rcarson** [comment]
It sounds like <code>robot.eavesdrop</code> should check every <code>Message</code> regardless if <code>Message.done == true</code>?

**Comment by technicalpickles** [comment]
> sounds like robot.eavesdrop should check every Message regardless if Message.done == true?

That would be a departure from how all the other listeners work, so I'm not sure if that's a good idea. Most often, I've used msg.done() to prevent any other scripts from processing.

**Comment by michaelansel** [comment]
The problem here isn't whether or not `message.done == true`; the CatchAllMessage is blocked if any `Listener.matcher` returns true when called with the Message.

A quick fix to this problem would be wrapping the TextListener matcher with a negative test (reject if matches respondPattern), but I think a refactor is in order around Listener matching (multiple open issues around custom match logic - this, #683). I'm not sure if receive middleware is the right long-term solution, but I'm in favor of a quick fix for now while we think about a larger refactor.

When I get a chance, I'm going to put together a flow chart for the message processing flow... [The new docs](https://github.com/github/hubot/pull/803/files#diff-a96ce3615ca004d0d25e5b3c2a91d6bdR13) in #803 don't quite cover everything.

For the quick fix, I think you can just extend TextListener with a new class (`EavesdropListener`?) that includes the added check, and then copy `robot.hear` to `robot.eavesdrop` and `s/TextListener/EavesdropListener/g`

**Comment by bkeepers** [comment]
It looks like the catch-all handling in https://github.com/github/hubot/pull/803 should solve this. Let me know if that's not the case.
