### ISSUE TITLE
impossible to use Hubot and receive secured webhook data

### ISSUE THREAD

**Issue by xrd** [github/hubot#923]
I'm trying to use [secure webhooks](https://developer.github.com/webhooks/securing/) with Hubot.

I believe I have the correct algorithm for decrypting once I have the body content.

```
getSecureHash = ( body ) ->
        hmac = crypto.createHmac( 'sha1', _SECRET )
        hmac.setEncoding( 'hex' )
        hmac.write( body )
        hmac.end()
        hash = hmac.read()
        console.log "Hash: #{hash}"
        hash
```

However, if I understand correctly, I need to use the original complete body as sent into the HTTP request (something like `payload=%7B%22ref%22%3A%22refs%2Fheads%2F14...`) and verify that computing the HMAC hash matches the signature sent in the HTTP_X_HUB_SIGNATURE header.

However, Hubot does not (AFAICT) allow you to customize the middleware used by express. And, the bodyParser does not provide the raw body inside the request object. It does parse it as JSON and provide you with that as an inflated object inside the request object.

However, the JSON once parsed does not allow me to stringify it again and guarantee that it will match the original pre-parsed body. In other words, once the JSON is parsed by express, I lose any significant whitespace that was inside the URL encoded JSON string, and that whitespace will change the HMAC hash such that after a roundtrip I have no chance of matching HMAC signatures.

Is there a way to get the raw body content inside my router callback? If not, it seems like securing the webhook is not possible with Hubot.

**Comment by sukima** [comment]
@xrd I can confirm this is the case. The bodyParser middleware gobbles up the data in the req stream. So the parsed result is available on `req.body` but the original raw body (the buffer data needed to compare the HMAC) is exhausted.

The only way to do this is to have a custom pass through middleware that will build the HMAC for you. Obviously Hubot core would need to be changed. Also since a custom webhook endpoint would have different secret keys there would have to be some mechanism to tell Hubot (and essentially the custom middleware) which key to use.

A double edged sword since `robot.router` is a reference to the express router allowing you to add your own middleware (`robot.router.use(…)`). However, the crux is that any use in a Hubot script is *after* the bodyParser middleware and the request stream would already have been exhausted.

And now I've rambled on till I've reached the conclusion that meta programming is the answer (add Hubot specific methods to the express.Router prototype). And at 2AM in the morning I'm way to tired for such thought experiments.

So yeah, If you thought GitHub's secure webhooks were a cool idea for your Hubot instance your pretty much :poop: out of luck at the moment.

**Comment by francof** [comment]
more on the subject here: http://stackoverflow.com/questions/18710225/node-js-get-raw-request-body-using-express

**Comment by brodul** [comment]
I also run into this problem. I tried to add my own middleware but as @sukima pointed out its to late because the order of middleware added is important.

One solution would be to add an additional attribute to the req object before other middlewares apply.

An idea. Usually its not hard to put a reverse proxy in front of hubot. So you can check the IP the webhook is coming from. Github has an IP list of subnetworks it uses https://help.github.com/articles/what-ip-addresses-does-github-use-that-i-should-whitelist/. So you can deny all hooks that are coming from other networks in apache2/nginx/whatever .  :smile:

**Comment by brodul** [comment]
I am working on this. Pull request with tests and documentation will be submitted today.

**Comment by Mike-Dunton** [comment]
@brodul How is the pull request coming along? This is something I would very much like to see fixed. Is there any way I could help

**Comment by Mike-Dunton** [comment]
Just leaving a reference to this Issue https://github.com/github/hubot/issues/765

 it solved my issues.
