### ISSUE TITLE
Do all listener endpoints really always need to start with /hubot?

### ISSUE THREAD

**Issue by victorhooi** [github/hubot#948]
_NB: Can somebody please apply the "question" label to this? For some odd reason, can't seem to find a way to do it from the issue creation form_

In the Hubot scripting guide (https://github.com/github/hubot/blob/f672bc03cf4bf415ce45ed60c38334d988fae8f4/docs/scripting.md), it mentions that:

> All endpoint URLs should start with the literal string /hubot (regardless of what your robot's name is). This consistency makes it easier to set up webhooks (copy-pasteable URL) and guarantees that URLs are valid (not all bot names are URL-safe).

Apart from the issue that your bot name might not be URL-safe, is there any other reason that the endpoint should begin with `/hubot`.

For example, if your bot name is just say, `james`, wouldn't `/james/foobar` be a perfectly valid endpoint?

Or are there other reasons to start all endpoints with `/hubot` as well?

Secondly - there's no issue with having multiple endpoints, in different scripts, are there? (e.g. `/james/foobar/cats`, `/james/croak/frog` etc.)

**Comment by technicalpickles** [comment]
> Apart from the issue that your bot name might not be URL-safe, is there any other reason that the endpoint should begin with /hubot.

There are two reasons for it:

* predictability of URLs. If you have offer a service that has hubot integration, you can refer to the URL without worrying about a
* valid(ish) URLs: depending on your chat service, there's a large range of robot names. but not all of them are necessarily valid URLs. Before hubot, I had a robot in campfire named "Mr. Robot". If I ported it directly to hubot and had URLs, it would be URLs like "http://whatever/Mr. Robot/foobar". That's probably not the best example since it's still valid, but you depending on what frameworks you use, having spaces isn't normal, and not having dots except to indicate a format.

> Secondly - there's no issue with having multiple endpoints, in different scripts, are there? (e.g. /james/foobar/cats, /james/croak/frog etc.)

No. There aren't a lot of open source scripts that use it, so there hasn't been much concern around endpoint overloading. It's expressjs under the hood, and I'm not sure how it behaves if you register the same endpoint multiple times.

**Comment by victorhooi** [comment]
Awesome, thanks for clearing that up =).

To be honest, this is an internal Hubot deployment, and we're unlikely to share these scripts externally (simply because they're not really useful outside the org). And the name in this case is "glados", which I believe would be valid in all cases for which "hubot" is.

Then again, "/hubot/<foo>" versus "/glados/<foo" isn't that big a deal, and I suppose we could just use "/hubot" if that's how things are done.
