### ISSUE TITLE
robot.respond to respond only once

### ISSUE THREAD

**Issue by ambikads** [github/hubot#950]
I am new to hubot. I am building a chat program where the hubot asks series of questions and user replies with answers. The regex used could be the same in hubot's questions. The user reply should only match the asked question and not all the matches. How can I accomplish this? 

example
Hubot> Your first name?
User> anything
Hubot> Your last name?
User> Anything

The regex I use is just (.*). This matches both the questions here and I get replies from both the listeners.

Thanks.

**Comment by michaelansel** [comment]
The short answer is: it's hard and there isn't a pre-existing pattern for this type of behavior.

If you're interested in putting in some development work, I imagine there is an opportunity to make a pretty cool framework to enable Q&A scripts. With the addition of listener options (#801, #803), you could register a listener, wait for a single response, and then destroy the listener. You might also need complex matchers (side effect of #871) so that another user's message or a message in another room isn't mistakenly matched.

No clue when the linked PRs will merge, but you can probably start developing against the general construct and tweak the interface if it changes.

**Comment by michaelansel** [comment]
#801 has merged and I pulled the complex matcher logic out of #871 into #986. As soon as #986 merges, you should be good to go for building this.

**Comment by michaelansel** [comment]
cc #319 which was also looking at ways to restrict listeners to specific rooms (or other complex conditions)

**Comment by mose** [comment]
Seems `robot.listen` brought a nice way out of this issue. I'm closing it.

**Comment by technicalpickles** [comment]
I've seen https://github.com/lmarkus/hubot-conversation come up a few times which is in this space.

I could see something like this becoming a more first class part of hubot. If anyone is interested in working on that, [Hubot Evolution](https://github.com/hubotio/evolution) is how we are handling new feature proposals.

**Comment by michaelansel** [comment]
Cross referencing a SO answer I just put together on the same topic: https://stackoverflow.com/questions/43600466/hubot-nesting-commands/44145694#44145694
