### ISSUE TITLE
HTTP Auth other than Basic? (Also, why node-scoped-http-client versus e.g. request?)

### ISSUE THREAD

**Issue by victorhooi** [github/hubot#957]
The [node-scoped-http-client](https://github.com/technoweenie/node-scoped-http-client) that Hubot exposes doesn't appear to support any kind of HTTP auth beyond Basic. (In my case, I'd like to use Digest auth)

Is there any way to somehow wrangle in other Auth formats (e.g. Digest) still using Hubot's exposed `http` object?

Also, I noticed that node-scoped-http-client is apparently unmaintained - is there a reason that Hubot doesn't move to another Node HTTP client wrapper that is supported - e.g. https://github.com/request/request?

**Comment by technicalpickles** [comment]
>  I noticed that node-scoped-http-client is apparently unmaintained

I wouldn't say it's unmaintained. I prefer the term 'undermaintained'. I watch the repo, and have merged PRs, but It hasn't needed a ton of work.

> is there a reason that Hubot doesn't move to another Node HTTP client wrapper that is supported

I'm not sure of the timeline, but I doubt it existed when hubot started, and if it was, it wasn't quite as prelevant.

As far as moving to it, it'd be quite a pain for the hubot ecosystem, because so many scripts are tied to that syntax. There'd need to be some backwards compatibility to allow existing scripts to continue working, because it'd be too much maintenance burden to inflict on users to port their code over when it is working well in most cases.

Since it's just a node library, there's nothing stopping script authors from adding it as a dependency and using it. In fact, [scripting.md](https://github.com/github/hubot/blob/master/docs/scripting.md#advanced-http-and-https-settings) suggests if it doesn't fit your needs.
