### ISSUE TITLE
Define and document testing patterns for scripts

### ISSUE THREAD

**Issue by michaelansel** [github/hubot#985]
Unit testing of scripts is pretty poor right now and there is no recommendation in the documentation on how testing should be done.

There are some thoughts in #873 about a new script pattern that might better enable testing.

We need a pattern that enables both unit testing of script components and functional testing of the overall script. It would be nice if functional tests could be reused by a larger test harness.

Some code that looks useful:
https://github.com/mtsmfm/hubot-test-helper
https://github.com/blalor/hubot-mock-adapter

Once a pattern gets figured out, we should bake it into the generator.

**Comment by michaelansel** [comment]
Whoops, completely forgot about github/generator-hubot#45

**Comment by technicalpickles** [comment]
:100: :x: :+1: 

I've mentioned elsewhere we're using the hubot-mock-adapter, with some helpers. It's a pretty simple framework on top of it, so probably can be extracted. Here's an example script with test and the helper: https://gist.github.com/technicalpickles/971b40520fb8db63a6f4

**Comment by ghostsquad** [comment]
:100: :+1: This is very much needed. I don't think I can even use Hubot for all the things I want to do, because it is difficult/convoluted to try to test it. These workflows include:

Incoming webhook -> Channel message or attachment
Incoming webhook -> Private message
Incoming webhook -> private/public message -> Outgoing webhook
private/public message -> Outgoing webhook

I think it might just be easier to make my own smaller bot. It won't do as much or have access to all the community scripts (without porting them), but at the same time, it doesn't need to.

I've read up on the hubot-test-helper and hubot-mock-adapter.

**Comment by mdelagrange** [comment]
I was recently upgrading our Hubot instance and tests, and https://github.com/mtsmfm/hubot-test-helper worked great!  So far it's the only working test framework I've found.  I wrote an article about it [here](https://github.com/mtsmfm/hubot-test-helper).

**Comment by michaelansel** [comment]
@mdelagrange I think you mixed up your links. You double linked to the GitHub repo. Looking forward to reading the article!

**Comment by mdelagrange** [comment]
Oops, thanks @michaelansel.  Fixed!

**Comment by michaelansel** [comment]
Excellent writeup! Hopefully that can get people building some form of tests until we develop an official pattern (unless you would like to do that! :wink:)

**Comment by mdelagrange** [comment]
I'd love to take a crack at it.  I'll give it a go soon.

**Comment by mdelagrange** [comment]
I have a couple of pull requests open for Hubot testing patterns.  github/generator-hubot#61 adds testing of Hubot responses to the script generator, and #1094 shows sample tests for the default script from the robot generator.
